version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27117:27017"
    volumes:
      - ./data/mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ajbear1969

  api:
    image: production-anslysis-service
    volumes:
      - ./flow:/app/flow
    ports:
      - "2300:2300"
    environment:
      MONGO_URI: mongodb://admin:ajbear1969@mongodb:27017
      ENDPOINT_URL: http://host.docker.internal:3303/api/interfaces/update
    depends_on:
      - mongodb

  client:
    image: production-anslysis-dashboard
    ports:
      - "8000:3000"
    environment:
      REACT_APP_BACKEND_API_ENDPOINT: http://api:2300
    command: npm start
    depends_on:
      - api

networks:
  default:
    driver: bridge
